name: My first Workflow

on : push   # it will push whenever there is push event

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My first Github Actions Job"
      - name: List files
        run: ls -l

      - name: Read file
        run: cat README.md



  